FROM node:20

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

COPY realtime-avatar/client/package.json realtime-avatar/client/pnpm-lock.yaml* ./

RUN pnpm install

COPY realtime-avatar/client ./

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "5173"]
